#!/bin/bash

all:
	@echo "Compiling..."
	javac -d build src/Model/*.java src/View/*.java src/Control/*.java src/*.java
	@echo "Compiling done"
	@echo "Running..."
	java -cp build Main
	@echo "Running done"
